[project]
name = "power-demand-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kein Takahashi", email = "keintakahashi092607@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jpholiday>=1.0.3",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[project.scripts]
power-demand-analysis = "power_demand_analysis:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyterlab>=4.6.3",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]
